# 服务端口
server:
  port: 8001

#服务名称
spriing:
  applocation:
    name:cloud-payment-service  #服务名称
spring:
  datasource:   #数据库配置
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver  # mysql驱动包
#    driver-class-name: org.gjt.mm.mysql.Driver  # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.summer.springcloud.entries
